name = "gsoc-contributors"
kind = "marker-team"

[people]
leads = []
members = [
    "Oneirical",
    "FractalFir",
    "Sa4dUs",
    "dawidl022",
    "namanlp",
    "zjp-CN",
    "GlitchlessCode",
    "madhav-madhusoodanan",
    "Sakib25800",
    "Shourya742",
    "lapla-cogito",
    "LorrensP-2158466",
    "CLIDragon",
    "FranciscoTGouveia",
    "mbyx",
    "DriedYellowPeach",
    "makai410",
    "Pyr0de",
    "secona",
    # KMJ-007 is participating in LLVM GSoC 2025, but they are working on Rust related things
    # Therefore, we include them here to give them access to the dev desktops
    { github = "KMJ-007", roles = ["guest"] },
]
alumni = [
    "d-sonuga",
    "mav3ri3k",
    "s7tya",
    "ding-young",
    "suaviloquence",
    "tiif",
    "shannmu"
]

[permissions]
dev-desktop = true
bors.rust.try = true
perf = true

[[roles]]
id = "guest"
description = "External GSoC contributor"

[[zulip-groups]]
name = "gsoc-contributors"
