name = "mentors"
kind = "marker-team"
subteam-of = "mentorship"

[people]
leads = []
members = [
    "Kobzol",
    "jackh726",
    "Amanieu",
    "epage",
    "jieyouxu",
    "ytmimi",
    "oli-obk",
    "obi1kenobi",
    "davidlattimore",
    "ZuseZ4",
    "tautschnig",
    "antoyo",
    "onur-ozkan",
    "SparrowLii",
    "rami3l",
    "tgross35",
    "Veykril",
    "celinval",
    "cassaundra"
]
alumni = []

[[zulip-groups]]
name = "gsoc-mentors"

[website]
name = "Mentors team"
description = "Mentors for the mentorship and internship programs"
