allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
    "rust-embedded.org",
    "rustconf.com",
]

allowed-github-orgs = [
    "rust-lang",
    "rust-lang-nursery",
    "rust-lang-deprecated",
    "rust-dev-tools",
    "rust-embedded",
    "rust-analyzer",
]

permissions-bors-repos = [
    "bors-kindergarten",
    "rust",
]

permissions-bools = [
    "perf",
    "crater",
    "crates-io-admin",
    "dev-desktop",
    "sync-team-confirmation",
]
