org = "rust-analyzer"
name = "expect-test"
description = "Minimalistic snapshot testing for Rust."
bots = []

[access.teams]
rust-analyzer = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["test"]
