org = "rust-lang"
name = "compiler-team"
description = "A home for compiler team planning documents, meeting minutes, and other such things."
homepage = "https://rust-lang.github.io/compiler-team/"
bots = ["rustbot", "rfcbot"]

[access.teams]
compiler = "write"
compiler-ops = "write"
types = "write"

[[branch-protections]]
pattern = "master"
required-approvals = 0
