org = "rust-lang"
name = "homu"
description = "A bot that integrates with GitHub and your favorite continuous integration service"
bots = []

[access.teams]
infra = "triage"
infra-admins = "write"

[[branch-protections]]
pattern = "master"
ci-checks = []
