org = "rust-lang"
name = "josh-sync"
description = "Utilities for synchronizing Josh subtrees to the Rust compiler repo"
bots = []

[access.teams]
compiler = "write"
infra = "write"

[[branch-protections]]
pattern = "main"
ci-checks = ["Test"]
required-approvals = 0
