org = "rust-lang"
name = "wg-allocators"
description = "Home of the Allocators working group: Paving a path for a standard set of allocator traits to be used in collections!"
homepage = "http://bit.ly/hello-wg-allocators"
bots = []

[access.teams]
libs = "write"
libs-api = "write"
libs-contributors = "write"
wg-allocators = "maintain"
