name = "wg-binary-size"
kind = "working-group"
subteam-of = "compiler"

[people]
leads = []
members = []

alumni = [
    "Kobzol",
    "antoyo",
    "davidtwco",
    "m-ou-se",
    "nbdd0121",
    "nnethercote",
    "tgross35",
    "thomcc",
    "workingjubilee"
]

[permissions]
bors.rust.try = true
perf = true

[[github]]
orgs = ["rust-lang"]

[website]
name = "Binary size working area"
description = "Improving the binary size of Rust programs and libraries"
repo = "https://github.com/rust-lang/wg-binary-size"
zulip-stream = "wg-binary-size"

[[zulip-groups]]
name = "wg-binary-size"